language: python
python:
    - "3.6"

services:
    - docker

before_script: pip install docker-compose

branches:
    only:
        - master

import:
    - source: .travis/push.yml
    if: type = push
    - source: .travis/pull.yml
    if: type = pull